/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menghitungdurasitidur;

import javax.swing.JOptionPane;

/**
 *
 * @author yahya abdillah
 */
public class tampilan extends javax.swing.JFrame {

    /**
     * Creates new form tampilan
     */
    public tampilan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        panelaplikasi = new javax.swing.JPanel();
        txtnama = new javax.swing.JTextField();
        txtgender = new javax.swing.JComboBox<>();
        jamtidur = new javax.swing.JTextField();
        jambangun = new javax.swing.JTextField();
        tombol = new javax.swing.JButton();
        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        judul3 = new javax.swing.JLabel();
        judul4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(132, 196, 236));
        setResizable(false);

        frame.setBackground(new java.awt.Color(0, 153, 255));
        frame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        judul.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("Aplikasi Menghitung Durasi Tidur");
        judul.setToolTipText("");

        panelaplikasi.setBackground(new java.awt.Color(51, 153, 255));
        panelaplikasi.setForeground(new java.awt.Color(51, 204, 255));

        txtnama.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        txtnama.setToolTipText("masukkan nama anda"); // NOI18N
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtgender.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        txtgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "balita", "remaja", "dewasa" }));
        txtgender.setToolTipText("");

        jamtidur.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jamtidur.setToolTipText("");

        jambangun.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jambangun.setToolTipText("");

        tombol.setBackground(new java.awt.Color(102, 102, 255));
        tombol.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        tombol.setText("Hitung Sekarang");
        tombol.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tombol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolActionPerformed(evt);
            }
        });

        judul1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 10)); // NOI18N
        judul1.setForeground(new java.awt.Color(255, 255, 255));
        judul1.setText("masukkan nama anda");
        judul1.setToolTipText("");

        judul2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 10)); // NOI18N
        judul2.setForeground(new java.awt.Color(255, 255, 255));
        judul2.setText("masukkan gender anda");
        judul2.setToolTipText("");

        judul3.setFont(new java.awt.Font("Montserrat SemiBold", 1, 10)); // NOI18N
        judul3.setForeground(new java.awt.Color(255, 255, 255));
        judul3.setText("masukkan jam tidur anda (24 jam)");
        judul3.setToolTipText("");

        judul4.setFont(new java.awt.Font("Montserrat SemiBold", 1, 10)); // NOI18N
        judul4.setForeground(new java.awt.Color(255, 255, 255));
        judul4.setText("masukkan jam bangun anda (24 jam)");
        judul4.setToolTipText("");

        javax.swing.GroupLayout panelaplikasiLayout = new javax.swing.GroupLayout(panelaplikasi);
        panelaplikasi.setLayout(panelaplikasiLayout);
        panelaplikasiLayout.setHorizontalGroup(
            panelaplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelaplikasiLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(tombol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelaplikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelaplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jambangun, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jamtidur)
                    .addComponent(judul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(judul2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(judul3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(judul4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelaplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelaplikasiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtnama)
                    .addContainerGap()))
        );
        panelaplikasiLayout.setVerticalGroup(
            panelaplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelaplikasiLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(judul1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(judul2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jamtidur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(judul4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jambangun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombol, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(panelaplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelaplikasiLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(242, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout frameLayout = new javax.swing.GroupLayout(frame);
        frame.setLayout(frameLayout);
        frameLayout.setHorizontalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelaplikasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        frameLayout.setVerticalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelaplikasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void tombolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolActionPerformed


    String nama = txtnama.getText();
    String gender = txtgender.getSelectedItem().toString();
    String tidur = jamtidur.getText();
    String bangun = jambangun.getText();

    int numtidur = Integer.parseInt(tidur);
    int numbangun = Integer.parseInt(bangun);
    int hasil;
    if (numtidur >= numbangun) {
        hasil = (24 - numtidur) + numbangun ;
    } else {
        hasil = numtidur - numbangun;
    }
    
    String ket;
    if (gender == "balita" && hasil >= 17){
        ket = "optimal";
    }
    else if (gender == "remaja" && hasil >= 9){
        ket = "optimal";
    }
    else if (gender == "dewasa" && hasil >= 8){
        ket = "optimal";
    }
    else {
        ket = "tidak optimal";
    }
    
    if (hasil >= 24){
        JOptionPane.showMessageDialog(this, "isikan data dengan benar");
    } else{
        JOptionPane.showMessageDialog(this, "jam tidur " + nama + " adalah " + ket);
    
    }
// TODO add your handling code here:
    }//GEN-LAST:event_tombolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel frame;
    private javax.swing.JTextField jambangun;
    private javax.swing.JTextField jamtidur;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel judul4;
    private javax.swing.JPanel panelaplikasi;
    private javax.swing.JButton tombol;
    private javax.swing.JComboBox<String> txtgender;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
